# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from gl_implement.MOGL import GLWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 700)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 700))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.openGLWidget = GLWidget(self.centralwidget)
        self.openGLWidget.setMinimumSize(QtCore.QSize(800, 600))
        self.openGLWidget.setMaximumSize(QtCore.QSize(800, 600))
        self.openGLWidget.setObjectName("openGLWidget")
        self.horizontalLayout.addWidget(self.openGLWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(200, 15))
        self.label.setMaximumSize(QtCore.QSize(200, 20))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setMinimumSize(QtCore.QSize(300, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(200, 15))
        self.label_2.setMaximumSize(QtCore.QSize(200, 20))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setMinimumSize(QtCore.QSize(300, 0))
        self.comboBox_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout.addWidget(self.comboBox_2)
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setMinimumSize(QtCore.QSize(300, 0))
        self.horizontalSlider.setMaximumSize(QtCore.QSize(300, 16777215))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout.addWidget(self.horizontalSlider)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(200, 20))
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMaximumSize(QtCore.QSize(200, 20))
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_2.setMinimumSize(QtCore.QSize(300, 0))
        self.horizontalSlider_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.verticalLayout.addWidget(self.horizontalSlider_2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMaximumSize(QtCore.QSize(200, 20))
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalSlider_3 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_3.setMinimumSize(QtCore.QSize(300, 0))
        self.horizontalSlider_3.setMaximumSize(QtCore.QSize(300, 16777215))
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.verticalLayout.addWidget(self.horizontalSlider_3)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMaximumSize(QtCore.QSize(200, 15))
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMaximumSize(QtCore.QSize(200, 15))
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setMinimumSize(QtCore.QSize(300, 0))
        self.comboBox_3.setMaximumSize(QtCore.QSize(300, 16777215))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.verticalLayout.addWidget(self.comboBox_3)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setMaximumSize(QtCore.QSize(200, 15))
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setMinimumSize(QtCore.QSize(300, 0))
        self.comboBox_4.setMaximumSize(QtCore.QSize(300, 16777215))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.verticalLayout.addWidget(self.comboBox_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Лабораторная работа №2"))
        self.label.setText(_translate("MainWindow", "Модификатор"))
        self.comboBox.setItemText(0, _translate("MainWindow", "GL_POINT"))
        self.comboBox.setItemText(1, _translate("MainWindow", "GL_LINES"))
        self.comboBox.setItemText(2, _translate("MainWindow", "GL_LINE_STRIP"))
        self.comboBox.setItemText(3, _translate("MainWindow", "GL_LINE_LOOP"))
        self.comboBox.setItemText(4, _translate("MainWindow", "GL_TRIANGLES"))
        self.comboBox.setItemText(5, _translate("MainWindow", "GL_TRIANGLE_STRIP"))
        self.comboBox.setItemText(6, _translate("MainWindow", "GL_TRIANGLE_FAN"))
        self.comboBox.setItemText(7, _translate("MainWindow", "GL_QUADS"))
        self.comboBox.setItemText(8, _translate("MainWindow", "GL_QUAD_STRIP"))
        self.comboBox.setItemText(9, _translate("MainWindow", "GL_POLYGON"))
        self.label_2.setText(_translate("MainWindow", "Тест прозрачности "))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "GL_NEVER"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "GL_LESS"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "GL_EQUAL"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "GL_LEQUAL"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "GL_GREATER"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "GL_NOTEQUAL"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "GL_GEQUAL"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "GL_ALWAYS"))
        self.label_3.setText(_translate("MainWindow", "Тест отсечения"))
        self.label_4.setText(_translate("MainWindow", "X"))
        self.label_5.setText(_translate("MainWindow", "Y"))
        self.label_6.setText(_translate("MainWindow", "Тест смешения цветов"))
        self.label_7.setText(_translate("MainWindow", "sfactor"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "GL_ZERO"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "GL_ONE"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "GL_DST_COLOR"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "GL_ONE_MINUS_DST_COLOR"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "GL_SRC_ALPHA"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "GL_ONE_MINUS_SRC_ALPHA"))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "GL_DST_ALPHA"))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "GL_ONE_MINUS_DST_ALPHA"))
        self.comboBox_3.setItemText(8, _translate("MainWindow", "GL_SRC_ALPHA_SATURATE"))
        self.label_8.setText(_translate("MainWindow", "dfactor"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "GL_ZERO"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "GL_ONE"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "GL_SRC_COLOR"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "GL_ONE_MINUS_SRC_COLOR"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "GL_SRC_ALPHA"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "GL_ONE_MINUS_SRC_ALPHA"))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "GL_DST_ALPHA"))
        self.comboBox_4.setItemText(7, _translate("MainWindow", "GL_ONE_MINUS_DST_ALPHA"))
